import os
from dotenv import load_dotenv

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL")
BREVO_KEY = os.getenv("BRAVO_API_KEY")
UPSTASH_REDIS_REST_URL=os.getenv("UPSTASH_REDIS_REST_URL")
UPSTASH_REDIS_REST_TOKEN = os.getenv("UPSTASH_REDIS_REST_TOKEN")
REDIS_URL = os.getenv("REDIS_URL")

JWT_ACCESS_TOKEN_SECRECT=os.getenv("JWT_ACCESS_TOKEN_SECRECT")
JWT_REFRESH_TOKEN_SECRET=os.getenv("JWT_REFRESH_TOKEN_SECRET")
JWT_ACCESS_TOKEN_EXPIRE_MINUTES=os.getenv("JWT_ACCESS_TOKEN_EXPIRE_MINUTES")
JWT_REFRESH_TOKEN_EXPIRE_DAYS=os.getenv("JWT_REFRESH_TOKEN_EXPIRE_DAYS")

JWT_ALGORITHM=os.getenv("JWT_ALGORITHM")

